In [1]:
import pandas as pd

In [2]:
X = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/x_train_gr_smpl.csv')

In [3]:
y = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl.csv')

In [4]:
y_0 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_0.csv')

In [5]:
y_1 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_1.csv')

In [6]:
y_2 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_2.csv')

In [7]:
y_3 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_3.csv')

In [8]:
y_4 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_4.csv')

In [9]:
y_5 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_5.csv')

In [10]:
y_6 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_6.csv')

In [11]:
y_7 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_7.csv')

In [12]:
y_8 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_8.csv')

In [13]:
y_9 = pd.read_csv('/home/swagmaster/Downloads/F21DL/CW1/original/y_train_smpl_9.csv')

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify = y)

In [16]:
X_0_train, X_0_test, y_0_train, y_0_test = train_test_split(X, y_0, 
                                                            test_size=0.33, random_state=42, stratify = y_0)

In [17]:
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X, y_1, 
                                                            test_size=0.33, random_state=42, stratify = y_1)

In [18]:
X_2_train, X_2_test, y_2_train, y_2_test = train_test_split(X, y_2, 
                                                            test_size=0.33, random_state=42, stratify = y_2)

In [19]:
X_3_train, X_3_test, y_3_train, y_3_test = train_test_split(X, y_3, 
                                                            test_size=0.33, random_state=42, stratify = y_3)

In [20]:
X_4_train, X_4_test, y_4_train, y_4_test = train_test_split(X, y_4, 
                                                            test_size=0.33, random_state=42, stratify = y_4)

In [21]:
X_5_train, X_5_test, y_5_train, y_5_test = train_test_split(X, y_5, 
                                                            test_size=0.33, random_state=42, stratify = y_5)

In [22]:
X_6_train, X_6_test, y_6_train, y_6_test = train_test_split(X, y_6, 
                                                            test_size=0.33, random_state=42, stratify = y_6)

In [23]:
X_7_train, X_7_test, y_7_train, y_7_test = train_test_split(X, y_7, 
                                                            test_size=0.33, random_state=42, stratify = y_7)

In [24]:
X_8_train, X_8_test, y_8_train, y_8_test = train_test_split(X, y_8, 
                                                            test_size=0.33, random_state=42, stratify = y_8)

In [25]:
X_9_train, X_9_test, y_9_train, y_9_test = train_test_split(X, y_9, 
                                                            test_size=0.33, random_state=42, stratify = y_9)

In [26]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.21919949968730457

In [27]:
y_0.columns = ['y']

In [28]:
y_0_corr_abs_ordered = X.corrwith(y_0.y).abs().sort_values(ascending = False)

In [29]:
y_1.columns = ['y']

In [30]:
y_1_corr_abs_ordered = X.corrwith(y_1.y).abs().sort_values(ascending = False)

In [31]:
y_2.columns = ['y']

In [32]:
y_2_corr_abs_ordered = X.corrwith(y_2.y).abs().sort_values(ascending = False)

In [33]:
y_3.columns = ['y']

In [34]:
y_3_corr_abs_ordered = X.corrwith(y_3.y).abs().sort_values(ascending = False)

In [35]:
y_4.columns = ['y']

In [36]:
y_4_corr_abs_ordered = X.corrwith(y_4.y).abs().sort_values(ascending = False)

In [37]:
y_5.columns = ['y']

In [38]:
y_5_corr_abs_ordered = X.corrwith(y_5.y).abs().sort_values(ascending = False)

In [39]:
y_6.columns = ['y']

In [40]:
y_6_corr_abs_ordered = X.corrwith(y_6.y).abs().sort_values(ascending = False)

In [41]:
y_7.columns = ['y']

In [42]:
y_7_corr_abs_ordered = X.corrwith(y_7.y).abs().sort_values(ascending = False)

In [43]:
y_8.columns = ['y']

In [44]:
y_8_corr_abs_ordered = X.corrwith(y_8.y).abs().sort_values(ascending = False)

In [45]:
y_9.columns = ['y']

In [46]:
y_9_corr_abs_ordered = X.corrwith(y_9.y).abs().sort_values(ascending = False)

In [47]:
def topNpixels(n):
    pix_0 = y_0_corr_abs_ordered.iloc[0:n].index
    pix_1 = pix_0.append(y_1_corr_abs_ordered.iloc[0:n].index)
    pix_2 = pix_1.append(y_2_corr_abs_ordered.iloc[0:n].index)
    pix_3 = pix_2.append(y_3_corr_abs_ordered.iloc[0:n].index)
    pix_4 = pix_3.append(y_4_corr_abs_ordered.iloc[0:n].index)
    pix_5 = pix_4.append(y_5_corr_abs_ordered.iloc[0:n].index)
    pix_6 = pix_5.append(y_6_corr_abs_ordered.iloc[0:n].index)
    pix_7 = pix_6.append(y_7_corr_abs_ordered.iloc[0:n].index)
    pix_8 = pix_7.append(y_8_corr_abs_ordered.iloc[0:n].index)
    return pix_8.append(y_9_corr_abs_ordered.iloc[0:n].index)

In [48]:
t5 = topNpixels(5)
X_train_t5, X_test_t5= X_train[t5], X_test[t5]

In [49]:
t10 = topNpixels(10)
X_train_t10, X_test_t10 = X_train[t10], X_test[t10]

In [50]:
t20 = topNpixels(20)
X_train_t20, X_test_t20 = X_train[t20], X_test[t20]

In [51]:
clf_5 = GaussianNB()
clf_5.fit(X_train_t5, y_train)
clf_5.score(X_test_t5, y_test)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.37367104440275173

In [52]:
clf_10 = GaussianNB()
clf_10.fit(X_train_t10, y_train)
clf_10.score(X_test_t10, y_test)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.350844277673546

In [53]:
clf_20 = GaussianNB()
clf_20.fit(X_train_t20, y_train)
clf_20.score(X_test_t20, y_test)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.32864290181363354

In [54]:
from sklearn.metrics import classification_report

In [58]:
X.astype(int)

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
0,78,77,76,82,87,92,104,119,117,120,...,87,79,72,76,83,95,99,98,95,94
1,73,75,79,78,76,75,89,107,133,125,...,96,93,85,77,69,73,83,100,101,101
2,72,75,79,77,81,89,105,109,86,90,...,98,95,88,80,73,71,74,80,89,95
3,67,70,74,80,93,107,110,96,69,100,...,112,92,87,82,77,72,70,72,81,88
4,74,74,73,72,77,87,104,109,84,83,...,100,98,99,100,99,89,78,66,68,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9685,247,220,254,213,129,208,254,255,255,255,...,35,29,27,26,25,23,22,26,26,27
9686,151,118,254,255,255,255,254,254,254,252,...,37,31,30,30,30,30,29,26,28,27
9687,255,255,255,255,255,255,255,255,255,255,...,41,49,42,36,33,36,39,31,39,43
9688,255,253,255,255,255,255,255,255,255,255,...,38,27,26,27,35,28,27,26,26,24
9689,252,189,238,255,255,245,219,212,140,40,...,34,23,23,30,32,23,23,26,20,17

In [63]:
y_pred = clf.predict(X_test)

In [109]:
rep = pd.DataFrame(classification_report(y_test, y_pred, output_dict = True)).T

In [112]:
acc = float(rep.loc[['accuracy'], 'precision'])

In [113]:
rep.loc[' '] = [None, None, None, None]

In [115]:
rep = rep.drop(index = 'accuracy')

              precision    recall  f1-score  support
0              0.148810  0.724638  0.246914     69.0
1              0.424749  0.173261  0.246124    733.0
2              0.426752  0.180350  0.253548    743.0
3              0.418327  0.225806  0.293296    465.0
4              0.477011  0.126911  0.200483    654.0
5              0.062731  0.246377  0.100000     69.0
6              0.084817  0.680672  0.150838    119.0
7              0.099537  0.544304  0.168297     79.0
8              0.433333  0.219101  0.291045    178.0
9              0.289474  0.247191  0.266667     89.0
macro avg      0.286554  0.336861  0.221721   3198.0
weighted avg   0.397234  0.219199  0.239842   3198.0
                    NaN       NaN       NaN      NaN

In [ ]:
rep

In [105]:
rep.loc['accuracy'] = [None, None, None,  acc]

In [108]:
rep.to_csv('rep.csv')

In [101]:
acc

0.21919949968730457

In [75]:
from sklearn.metrics import cohen_kappa_score

In [76]:
cohen_kappa_score(y_test, y_pred)

0.14427873598445906

In [77]:
from sklearn.metrics import confusion_matrix

In [80]:
pd.DataFrame(confusion_matrix(y_test, y_pred))

     0    1    2    3   4   5    6    7   8   9
0   50    1    7    8   0   0    0    3   0   0
1  200  127   98   31  22  27  124   88  10   6
2   46   99  134   71  50  88  127  110   3  15
3   16    6    5  105  16  37  237   10  26   7
4   13   59   58   31  83  64  292   49   0   5
5    3    0    1    0   0  17   16   26   6   0
6    0    1    0    1   0   7   81   15   0  14
7    0    0    4    3   0   0   24   43   0   5
8    8    6    6    0   0  17   47   53  39   2
9    0    0    1    1   3  14    7   35   6  22

In [57]:
from pomegranate import *

In [58]:
import numpy as np

In [60]:
X

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
0,78.0,77.0,76.0,82.0,87.0,92.0,104.0,119.0,117.0,120.0,...,87.0,79.0,72.0,76.0,83.0,95.0,99.0,98.0,95.0,94.0
1,73.0,75.0,79.0,78.0,76.0,75.0,89.0,107.0,133.0,125.0,...,96.0,93.0,85.0,77.0,69.0,73.0,83.0,100.0,101.0,101.0
2,72.0,75.0,79.0,77.0,81.0,89.0,105.0,109.0,86.0,90.0,...,98.0,95.0,88.0,80.0,73.0,71.0,74.0,80.0,89.0,95.0
3,67.0,70.0,74.0,80.0,93.0,107.0,110.0,96.0,69.0,100.0,...,112.0,92.0,87.0,82.0,77.0,72.0,70.0,72.0,81.0,88.0
4,74.0,74.0,73.0,72.0,77.0,87.0,104.0,109.0,84.0,83.0,...,100.0,98.0,99.0,100.0,99.0,89.0,78.0,66.0,68.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9685,247.0,220.0,254.0,213.0,129.0,208.0,254.0,255.0,255.0,255.0,...,35.0,29.0,27.0,26.0,25.0,23.0,22.0,26.0,26.0,27.0
9686,151.0,118.0,254.0,255.0,255.0,255.0,254.0,254.0,254.0,252.0,...,37.0,31.0,30.0,30.0,30.0,30.0,29.0,26.0,28.0,27.0
9687,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,41.0,49.0,42.0,36.0,33.0,36.0,39.0,31.0,39.0,43.0
9688,255.0,253.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,38.0,27.0,26.0,27.0,35.0,28.0,27.0,26.0,26.0,24.0
9689,252.0,189.0,238.0,255.0,255.0,245.0,219.0,212.0,140.0,40.0,...,34.0,23.0,23.0,30.0,32.0,23.0,23.0,26.0,20.0,17.0

In [59]:
np.array(X)

array([[ 78.,  77.,  76., ...,  98.,  95.,  94.],
       [ 73.,  75.,  79., ..., 100., 101., 101.],
       [ 72.,  75.,  79., ...,  80.,  89.,  95.],
       ...,
       [255., 255., 255., ...,  31.,  39.,  43.],
       [255., 253., 255., ...,  26.,  26.,  24.],
       [252., 189., 238., ...,  26.,  20.,  17.]])

In [109]:
from sklearn.cluster import KMeans

In [110]:
X

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
0,78.0,77.0,76.0,82.0,87.0,92.0,104.0,119.0,117.0,120.0,...,87.0,79.0,72.0,76.0,83.0,95.0,99.0,98.0,95.0,94.0
1,73.0,75.0,79.0,78.0,76.0,75.0,89.0,107.0,133.0,125.0,...,96.0,93.0,85.0,77.0,69.0,73.0,83.0,100.0,101.0,101.0
2,72.0,75.0,79.0,77.0,81.0,89.0,105.0,109.0,86.0,90.0,...,98.0,95.0,88.0,80.0,73.0,71.0,74.0,80.0,89.0,95.0
3,67.0,70.0,74.0,80.0,93.0,107.0,110.0,96.0,69.0,100.0,...,112.0,92.0,87.0,82.0,77.0,72.0,70.0,72.0,81.0,88.0
4,74.0,74.0,73.0,72.0,77.0,87.0,104.0,109.0,84.0,83.0,...,100.0,98.0,99.0,100.0,99.0,89.0,78.0,66.0,68.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9685,247.0,220.0,254.0,213.0,129.0,208.0,254.0,255.0,255.0,255.0,...,35.0,29.0,27.0,26.0,25.0,23.0,22.0,26.0,26.0,27.0
9686,151.0,118.0,254.0,255.0,255.0,255.0,254.0,254.0,254.0,252.0,...,37.0,31.0,30.0,30.0,30.0,30.0,29.0,26.0,28.0,27.0
9687,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,41.0,49.0,42.0,36.0,33.0,36.0,39.0,31.0,39.0,43.0
9688,255.0,253.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,38.0,27.0,26.0,27.0,35.0,28.0,27.0,26.0,26.0,24.0
9689,252.0,189.0,238.0,255.0,255.0,245.0,219.0,212.0,140.0,40.0,...,34.0,23.0,23.0,30.0,32.0,23.0,23.0,26.0,20.0,17.0

In [116]:
kmeans = KMeans(n_clusters=10, random_state=42, n_jobs = -1).fit(X)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:938: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"

In [117]:
kmeans.labels_.tolist()

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 7,
 7,
 7,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 8,
 8,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 0,
 3,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 0,
 7,
 7,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 0,
 0,
 3,
 0,
 0,
 9,
 9,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 9,
 9,
 9,
 9,
 0,
 0,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 0,
 9,
 0,
 0,
 0,
 0,
 0,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 3,
 7,
 3,
 3,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 7,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 3,
 3,
 3,
 3,
 7,
 3,
 5,
 5,
 5,
 5,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 6,
 6,
 6,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 3,
 3,
 5,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 0,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 0,
 0,
 0,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 ...]

In [119]:
kmeans.fit_predict(X)

/home/swagmaster/anaconda3/envs/f21dl/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:938: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"

array([3, 3, 3, ..., 8, 8, 8], dtype=int32)